
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import model.UserDAO;

/**
 *
 * @author Thanh
 */
public class HuongDanDialog extends javax.swing.JDialog {

    /**
     * Creates new form LoginDialog
     */
    public HuongDanDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents(); //phương thức tự định nghĩa được sử dụng để khởi tạo các thành phần của giao diện người dụng (GUI). Phương thức này thường chứa mã để thiết lập layout
        setLocationRelativeTo(null); //phương thức đặt cửa sổ hiển thị vào giữa màn hình 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("HƯỚNG DẪN SỬ DỤNG");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("**Script Hướng Dẫn Sử Dụng Phần Mềm BDS Vietland**\n\n1. Giới Thiệu:\n   \n   Chào mừng bạn đến với hướng dẫn sử dụng phần mềm BDS Vietland. Phần mềm này được thiết kế để giúp bạn quản lý thông tin bất động sản một cách hiệu quả và thuận tiện.\n\n2. Đăng Nhập:\n\n   - Bước 1: Mở phần mềm BDS Vietland trên máy tính của bạn.\n   - Bước 2: Nhập tên người dùng và mật khẩu của bạn vào các trường tương ứng.\n   - Bước 3: Nhấn vào nút \"Đăng nhập\" để truy cập vào hệ thống.\n\n3. Giao Diện Chính:\n\n   - Sau khi đăng nhập thành công, bạn sẽ thấy giao diện chính của phần mềm. Ở đây, bạn có thể thấy các tính năng chính như: Quản lý khách hàng, quản lý bất động sản, báo cáo, cài đặt, vv.\n\n4. Quản Lý Khách Hàng:\n\n   - Để thêm một khách hàng mới, bạn có thể nhấn vào nút \"Thêm khách hàng\" và nhập thông tin chi tiết của khách hàng vào các trường tương ứng.\n   - Bạn cũng có thể xem, chỉnh sửa hoặc xóa thông tin của khách hàng bằng cách chọn khách hàng trong danh sách và sử dụng các nút chức năng tương ứng.\n\n5. Quản Lý Bất Động Sản:\n\n   - Tương tự như quản lý khách hàng, bạn có thể thêm, xem, chỉnh sửa hoặc xóa thông tin về bất động sản trong phần mềm.\n   - Bạn cũng có thể tìm kiếm bất động sản dựa trên các tiêu chí như loại bất động sản, vị trí, giá cả, vv.\n\n6. Báo Cáo:\n\n   - Phần mềm cung cấp các báo cáo về tình hình kinh doanh của bạn như doanh số bán hàng, doanh thu, vv. Bạn có thể truy cập vào phần này để theo dõi hiệu suất kinh doanh của mình.\n\n7. **Cài Đặt:**\n\n   - Trong phần cài đặt, bạn có thể tùy chỉnh các cài đặt của phần mềm như ngôn ngữ, đơn vị tiền tệ, vv.\n\n8. **Thoát:**\n\n   - Để thoát khỏi phần mềm, bạn có thể nhấn vào nút \"Đăng xuất\" hoặc \"Thoát\" tùy thuộc vào cài đặt của bạn.\n\n9. **Hỗ Trợ:**\n\n   - Nếu bạn gặp bất kỳ vấn đề nào khi sử dụng phần mềm, vui lòng liên hệ với bộ phận hỗ trợ của chúng tôi để được giúp đỡ.\n\n---");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* phương thức kiểm tra xem form có hợp lệ hay không. 
    Nếu trường txtUserName hoặc txtPassword trống, phương thức này sẽ trả về false, 
    ngược lại, nếu cả hai trường đều không trống, nó sẽ trả về true. 
    Điều này có thể được sử dụng để ngăn chặn việc gửi form khi người dùng không nhập tên người dùng hoặc mật khẩu.*/
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HuongDanDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HuongDanDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HuongDanDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HuongDanDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HuongDanDialog dialog = new HuongDanDialog(new javax.swing.JFrame(), true); //Tạo một cửa sổ đăng nhập mới. Tham số true cho biết cửa sổ này là modal, tức là khi nó được hiển thị, người dùng không thể tương tác với các cửa sổ khác cho đến khi cửa sổ này bị đóng.
                dialog.addWindowListener(new java.awt.event.WindowAdapter() { //hêm một trình nghe sự kiện cửa sổ mới. Trong trường hợp này, nếu người dùng đóng cửa sổ, chương trình sẽ kết thúc (System.exit(0)).
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) { 
                        System.exit(0);
                    }
                });
                dialog.setVisible(true); //Hiển thị cửa sổ đăng nhập.
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
